version: '3.8'

services:
  # Aplicación principal
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: obratec-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
      - GOTENBERG_URL=http://gotenberg:3000
    networks:
      - obratec-network
    depends_on:
      - n8n
      - gotenberg

  # N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: obratec-n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=n8n.obratec.app
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://n8n.obratec.app
      - NODE_ENV=production
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Obratec2024!
      - N8N_ENCRYPTION_KEY=oJD95Mid3QZKSGl1wpVlWR2/3G688fqg+02JXNnt4Bk=
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - GENERIC_TIMEZONE=America/Santiago
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    networks:
      - obratec-network

  # Gotenberg para generación de PDFs
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: obratec-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-web-security"
      - "--chromium-allow-list=file://"
    networks:
      - obratec-network

volumes:
  n8n_data:
    driver: local

networks:
  obratec-network:
    driver: bridge
