# Docker Compose para VPS Hostinger - obratec.app
version: '3.8'

services:
  # Aplicación principal (Frontend + Proxy para N8N)
  app:
    build: .
    container_name: obratec-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
    volumes:
      - ./public:/app/public
    networks:
      - obratec-network
    depends_on:
      - n8n

  # N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: obratec-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Configuración básica
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      
      # Desactivar funciones innecesarias
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      
      # Base de datos SQLite
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      
      # Limpieza automática de ejecuciones
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      
      # Zona horaria
      - GENERIC_TIMEZONE=Europe/Madrid
      
      # URLs del sistema
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
      
      # API Keys (se cargan desde .env)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # Encriptación N8N
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    networks:
      - obratec-network

volumes:
  n8n_data:
    driver: local

networks:
  obratec-network:
    driver: bridge