# Docker Compose para VPS Hostinger - obratec.app
version: '3.8'

services:
  # Aplicación principal (Frontend + Proxy para N8N)
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: obratec-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
    networks:
      - obratec-network
    depends_on:
      - n8n

  # N8N Workflow Automation - CONFIGURACIÓN SEGURA
  n8n:
    image: n8nio/n8n:latest
    container_name: obratec-n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=https://n8n.obratec.app
      - NODE_ENV=production
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ObraTec2024!
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_ENCRYPTION_KEY=obratec_secure_key_2024
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
      - WEBHOOK_URL=https://obratec.app/webhook/form-obra
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "127.0.0.1:5678:5678"
    networks:
      - obratec-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:

networks:
  obratec-network:
    driver: bridge
